### ISSUE TITLE
Use pipeline parameters in the "approval" property

### ISSUE THREAD

**Issue by livanov** [tomzo/gocd-yaml-config-plugin#134] opened 2019-11-21 11:47 UTC
I have 2 pipelines - `deploy-dev` and `deploy-prod`. I have setup parameters in my stages, thus both the pipelines use the same stage list anchor.

```
deploy-dev:
  group: dev
  parameters:
    namespace-name: "my-app-dev"
  materials:
    # ...
  stages: *deploy-stage-list
```

However, what I'd like is for the `deploy-prod` pipeline is that my 3rd (out of 5 stages) to be with `approval: manual`. The syntax doesn't allow me to use parameters for this. I am getting "approval should be hash or string" error.

**Comment by adamMo** [comment] 2020-09-04 11:12
@tomzo I am thinking about developing it using environment variables - do you think it's right approach or you forsee some problems? It would make my life much easier to have such flexibility.

**Comment by arvindsv** [comment] 2020-09-04 11:46
Environment variables are usually resolved later in the cycle, after a pipeline is scheduled (and the value is used). It won't be straightforward and is a likely a conversation in GoCD core. https://github.com/gocd/gocd/issues/3 might be tangentially relevant.

**Comment by tomzo** [comment] 2020-09-13 14:27
I'm closing this, as the issue is really within the domain of core.

**Closed by tomzo** 2020-09-13 14:27 UTC
