### ISSUE TITLE
Error when working with Github Private Repo

### ISSUE THREAD

**Issue by michael-iglesias** [tomzo/gocd-yaml-config-plugin#79] opened 2018-08-13 17:10 UTC
For some reason GOCD isn't able to successfully poll and clone the repo. I've tried the following suggestions I've come across on multiple resources.

1. Generated SSH keys and copied to `/var/go/.ssh/id_rsa.pub`
1A. I've verified connection by running `$ ssh -vT git@github.com`
2. I've specified `https:<username>:<personal_access_token>@github.com/<org>/<repo> in both the `url` parameter within `<config_repo>` inside`config.xml and I've also included the same connection url within the git material specification within my `ci.gocd.yaml` file

I'm still sporadically receiving a `Failed to run git clone command STDERR.... Host Key Verification Failed`

Also, it might be worth noting that currently I'm developing on a feature branch `feature/ci-cd-pipeline` which I've listed within my gocd.yaml file under the material definition `branch: feature/ci-cd-pipeline`

Any suggestions would be greatly appreciated. I've been banging my head into the keyboard trying to figure this one out :(

GOCD Version: 18.3.0
Server & Agent running on same Ubuntu host

**Comment by tomzo** [comment] 2018-10-17 21:15
@michael-iglesias  Sorry for the late reply, but I was away when you posted this.

`Failed to run git clone command STDERR.... Host Key Verification Failed` is usually caused by having [invalid known_hosts file](https://stackoverflow.com/questions/4161548/how-to-establish-ssh-key-pair-when-host-key-verification-failed). You can workaround this by configuring ssh on server with
`~/.ssh/config`
```
StrictHostKeyChecking no
UserKnownHostsFile /dev/null
```
You mention https and ssh, but which one did you intend to use eventually?

I'll close this now, because:
 - the plugin is not responsible for cloning, or checkout. 
 - this is clearly a material and/or server configuration issue.

**Closed by tomzo** 2018-10-17 21:15 UTC
