### ISSUE TITLE
Support Pipeline templates

### ISSUE THREAD

**Issue by ArthurQQII** [tomzo/gocd-yaml-config-plugin#211] opened 2024-08-15 01:14 UTC
Hi,

I'm referring to GoCD pipeline templates, not the templates for creating pipeline YAML files. For more details, you can check out the [GoCD Pipeline Templates documentation](https://docs.gocd.org/current/configuration/pipeline_templates.html).

I'm trying to use the gocd-yaml-config-plugin to manage all my configurations in a Git repository, but I'm facing challenges when defining templates.

Is there a possibility that this feature could be supported in the future?

**Comment by chadlwilson** [comment] 2024-08-15 01:21
Duplicate of #2 and https://github.com/gocd/gocd/issues/5675

This cannot be implemented as described without core GoCD support within config repo plugins, so seems very unlikely, given the current state of maintenance for GoCD and all of the core plugins - and the earlier debate on whether this is even appropriate - since the pipeline template model has many limitations.

**Closed by chadlwilson** 2024-08-15 01:21 UTC

**Comment by chadlwilson** [comment] 2024-08-15 01:42
You might be interested in these threads on the Google groups. Probably others.

https://groups.google.com/g/go-cd/c/JalrejeFlOc/m/xpLsZGZLAgAJ
https://groups.google.com/g/go-cd/c/UDZPx4gieFE/m/9QqGXxB1CQAJ
